EventOrganiser/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include("main.urls")),
]

main/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("<int:id>", views.index, name="index"),
    path("",views.home,name="home"),
]

main/models.py
from django.db import models

# Create your models here.
class ToDoList(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name 
    
class Item(models.Model):
    todolist = models.ForeignKey(ToDoList,on_delete=models.CASCADE)
    text = models.CharField(max_length=300)
    complete = models.BooleanField()

    def __str__(self):
        return self.text

main/views.py
from django.shortcuts import render
from django.http import HttpResponse
from .models import ToDoList, Item

# Create your views here.

def index(response, id):
    ls = ToDoList.objects.get(id=id)
    return render(response, "main/list.html",{'ls':ls})

def home(response):
    return render(response, "main/home.html",{})

main/templates/main/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Event Organiser{% endblock %}</title>
</head>
<body>
    <div id="content", name="content">
        {% block content %}

        {% endblock %}
    </div>
</body>
</html>

main/templates/main/home.html
{% extends 'main/base.html' %}
{% block title %}Home{% endblock %}
{% block content %}
    <h1>Welcome to home page! </h1>
{% endblock %}

main/templates/main/list.html
{% extends 'main/base.html' %}
{% block title %}List{% endblock %}
    {% block content %}
        <h1>{{ls.name}}</h1>
        <ul>
            {% for item in ls.item_set.all %}
                {% if item.complete == False %}
                    <li>{{item.text}} - INCOMPLETE </li>
                {% else %}
                    <li> {{item.text}} - COMPLETE
                {% endif %}
            {% endfor %}
        </ul>
{% endblock %}